const LOOKBOOK_BASE = [
    {name:'烤雞腿', mat:'生雞腿', satiety:30},
    {name:'烤豬排', mat:'生豬排', satiety:50, hydration:-10},
    {name:'烤羊排', mat:'生羊排', satiety:40, hydration:-10},
    {name:'烤牛排', mat:'生牛排', satiety:40, hydration:-10},
    {name:'烤野味', mat:'野味肉塊', satiety:30, hydration:-10},
    {name:'烤雞蛋', mat:'生雞蛋', satiety:20, effect:'血量'},
    {name:'烤玉米', mat:'玉米', satiety:20, hydration:-5},
    {name:'烤蘑菇', mat:'蘑菇', satiety:10, hydration:-5},
    {name:'烤土豆', mat:'土豆', satiety:15, hydration:-10},
    {name:'烤南瓜', mat:'南瓜', satiety:15, hydration:-10},
    {name:'烤香蕉', mat:'香蕉', satiety:10},
    {name:'烤蘋果', mat:'蘋果', satiety:10},
    {name:'烤辣椒', mat:'辣椒'},
    {name:'烤龜蛋', mat:'龜蛋', satiety:30, hydration:-10},
    {name:'烤洋蔥', mat:'洋蔥', satiety:10},
    {name:'烤筍尖', mat:'竹筍', satiety:10},
    {name:'烤青椒', mat:'青椒', satiety:5},
    {name:'烤章魚', mat:'章魚', satiety:30, hydration:-10},
    {name:'烤大扇貝', mat:'大扇貝', satiety:20},
    {name:'烤小扇貝', mat:'小扇貝', satiety:10},
    {name:'烤帶魚', mat:'帶魚', satiety:30},
    {name:'烤三文魚', mat:'三文魚', satiety:30},
    {name:'烤金槍魚', mat:'金槍魚', satiety:30},
    {name:'烤紅鯉魚', mat:'紅鯉魚', satiety:30},
    {name:'烤綠鯉魚', mat:'綠鯉魚', satiety:30},
    {name:'烤綠鱸魚', mat:'綠鱸魚', satiety:30},
    {name:'烤鰻魚', mat:'鰻魚', satiety:30},
    {name:'烤鮫魚', mat:'鮫魚', satiety:30},
    {name:'烤桂魚', mat:'桂魚', satiety:30},
    {name:'炒瓜子', mat:'向日葵種子', satiety:10, hydration:-5},
    {name:'聖焰雞腿', mat:'生雞腿', satiety:30, effect:'攻擊'},
    {name:'聖焰豬排', mat:'生豬排', satiety:50, hydration:-10, effect:'防禦'},
    {name:'聖焰羊排', mat:'生羊排', satiety:40, hydration:-10, effect:'速度'},
    {name:'聖焰牛排', mat:'生牛排', satiety:40, hydration:-10, effect:'攻擊'},
    {name:'聖焰野味', mat:'野味肉塊', satiety:30, hydration:-10, effect:'防禦'},
    {name:'聖焰雞蛋', mat:'生雞蛋', satiety:20, effect:'血量'},
    {name:'聖焰玉米', mat:'玉米', satiety:20, hydration:-5, effect:'防禦'},
    {name:'聖焰蘑菇', mat:'蘑菇', satiety:10, hydration:-5, effect:'速度'},
    {name:'聖焰土豆', mat:'土豆', satiety:15, hydration:-10, effect:'攻擊'},
    {name:'聖焰南瓜', mat:'南瓜', satiety:15, hydration:-10, effect:'防禦'},
    {name:'聖焰香蕉', mat:'香蕉', satiety:10, effect:'速度'},
    {name:'聖焰蘋果', mat:'蘋果', satiety:10, effect:'攻擊'},
    {name:'聖焰辣椒', mat:'辣椒', effect:'禦寒'},
    {name:'聖焰龜蛋', mat:'龜蛋', satiety:30, hydration:-10, effect:'速度'},
    {name:'聖焰洋蔥', mat:'洋蔥', satiety:10, effect:'速度'},
    {name:'聖焰筍尖', mat:'竹筍', satiety:10, effect:'攻擊'},
    {name:'聖焰青椒', mat:'青椒', satiety:5, effect:'防禦'},
    {name:'聖焰章魚', mat:'章魚', satiety:30, hydration:-10, effect:'攻擊'},
    {name:'聖焰大扇貝', mat:'大扇貝', satiety:20, effect:'攻擊'},
    {name:'聖焰小扇貝', mat:'小扇貝', satiety:10, effect:'防禦'},
    {name:'聖焰帶魚', mat:'帶魚', satiety:30, effect:'攻擊'},
    {name:'聖焰三文魚', mat:'三文魚', satiety:30, effect:'防禦'},
    {name:'聖焰金槍魚', mat:'金槍魚', satiety:30, effect:'速度'},
    {name:'聖焰紅鯉魚', mat:'紅鯉魚', satiety:30, effect:'防禦'},
    {name:'聖焰綠鯉魚', mat:'綠鯉魚', satiety:30, effect:'速度'},
    {name:'聖焰綠鱸魚', mat:'綠鱸魚', satiety:30, effect:'攻擊'},
    {name:'聖焰鰻魚', mat:'鰻魚', satiety:30, effect:'防禦'},
    {name:'聖焰鮫魚', mat:'鮫魚', satiety:30, effect:'速度'},
    {name:'聖焰桂魚', mat:'桂魚', satiety:30, effect:'攻擊'},
    {name:'劍齒虎飼料*17', mat:['生牛排' ,'小龍蝦','飼餵肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'劍齒虎王飼料*13', mat:['小龍蝦' ,'生牛排', '優質肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'岩火劍齒虎飼料*30', mat:['大扇貝' ,'優質肉塊','稀有肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'岩火劍齒虎王飼料*35', mat:['大扇貝' ,'稀有肉塊','罕見肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'獅鷲飼料*110', mat:['鯊魚心臟' ,'精靈魚','罕見肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'暴力兔飼料*20', mat:['牛奶' ,'胡蘿蔔飼料包', '稀有肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'暴力兔王飼料*25', mat:['竹筍飼料包' ,'胡蘿蔔飼料包','罕見肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'藍蜥蜴飼料*5', mat:['藍蘑菇' ,'飼餵肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'紅蜥蜴飼料*5', mat:['紅蘑菇' ,'飼餵肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'狼王飼料*14', mat:['生羊排' ,'優質肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'沙漠狼飼料*13', mat:['生羊排' ,'土豆飼料包','飼餵肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'沙漠狼王飼料*15', mat:['生羊排' ,'土豆飼料包', '優質肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'雪原狼飼料*unknown', mat:['生羊排' ,'小麥飼料包', '飼餵肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'幼鯖鯊飼料*25', mat:['生羊排' ,'象拔蚌', '優質肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'灰鯖鯊飼料*60', mat:['小丑魚' ,'藍蓮飼料包', '稀有肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'虎皮鯊飼料*110', mat:['小丑魚' ,'金龍魚', '罕見肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'駱駝飼料*7', mat:['小麥飼料包' ,'玉米飼料包'], category:'飼料', building:'烹飪鍋'},
    {name:'小烏龜飼料*4', mat:['鯉魚' ,'小麥飼料包'], category:'飼料', building:'烹飪鍋'},
    {name:'岩漿海龜飼料*13', mat:['鯉魚' ,'大閘蟹'], category:'飼料', building:'烹飪鍋'},
    {name:'水池龜飼料*14', mat:['三文魚' ,'鯰魚'], category:'飼料', building:'烹飪鍋'},
    {name:'黑馬飼料*45', mat:['鮑魚' ,'小麥飼料包','藍蓮飼料包'], category:'飼料', building:'烹飪鍋'},
    {name:'紅馬飼料*13', mat:['小麥飼料包' ,'辣椒飼料包','優質肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'藍馬飼料*8', mat:['河豚' ,'小麥飼料包','玉米飼料包'], category:'飼料', building:'烹飪鍋'},
    {name:'沙豬飼料*1', mat:['小麥飼料包' ,'玉米飼料包'], category:'飼料', building:'烹飪鍋'},
    {name:'陸行鳥飼料*12', mat:['小麥飼料包' ,'胡蘿蔔飼料包'], category:'飼料', building:'烹飪鍋'},
    {name:'青色陸行鳥飼料*110', mat:['紅蓮飼料包' ,'洋蔥飼料包','罕見肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'大角牛飼料*20', mat:['小麥飼料包' ,'白蓮飼料包','稀有肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'大角牛王飼料*23', mat:['小麥飼料包' ,'白蓮飼料包','罕見肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'荒原牛飼料*6', mat:['甘蔗' ,'蘋果', '小麥飼料包'], category:'飼料', building:'烹飪鍋'},
    {name:'獨角獸飼料*120', mat:['精靈魚' ,'帝王蟹', '草莓飼料包'], category:'飼料', building:'烹飪鍋'},
    {name:'毒液龍飼料*20', mat:['生雞蛋' ,'毒蘑菇飼料包', '稀有肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'毒液龍王飼料*25', mat:['龜蛋' ,'毒蘑菇飼料包', '罕見肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'冰毒液龍飼料*50', mat:['冰精' ,'雞蛋飼料包', '北極冰魚飼料包'], category:'飼料', building:'烹飪鍋'},
    {name:'冰毒液龍王飼料*55', mat:['冰精' ,'龜蛋飼料包', '霜凍之花'], category:'飼料', building:'烹飪鍋'},
    {name:'棕熊飼料*13', mat:['草莓' ,'蜂蜜飼料包', '飼餵肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'棕熊大飼料*16', mat:['海帶' ,'帶魚', '小麥飼料包'], category:'飼料', building:'烹飪鍋'},
    {name:'藍熊大飼料*12', mat:['蜂蜜飼料包' ,'優質肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'雪原熊飼料*9', mat:['甘蔗' ,'小麥飼料包', '蜂蜜飼料包'], category:'飼料', building:'烹飪鍋'},
    {name:'雪原熊大飼料*13', mat:['蜂蜜飼料包' ,'優質肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'霸王龍飼料*15', mat:['松露' ,'土豆飼料包', '優質肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'暗黑霸王龍飼料*55', mat:['象拔蚌' ,'稀有肉塊','罕見肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'巨猿飼料*13', mat:['香蕉' ,'松果', '大閘蟹'], category:'飼料', building:'烹飪鍋'},
    {name:'猛瑪象飼料*13', mat:['松果','大龍蝦' ,'胡蘿蔔飼料包'], category:'飼料', building:'烹飪鍋'},
    {name:'雪猛瑪飼料*13', mat:['大龍蝦','玉米飼料包' ,'土豆飼料包'], category:'飼料', building:'烹飪鍋'},
    {name:'雲斑鸚鳥飼料*45', mat:['鮑魚' ,'小麥飼料包', '辣椒飼料包'], category:'飼料', building:'烹飪鍋'},
    {name:'上古顎龍飼料*55', mat:['鮑魚' ,'桂魚', '章魚'], category:'飼料', building:'烹飪鍋'},
    {name:'熔火龍飼料*110', mat:['龍涎草' ,'精靈魚','罕見肉塊'], category:'飼料', building:'烹飪鍋'},
    {name:'北境犀鳥飼料*110', mat:['冰精' ,'鰩魚', '冰河松果飼料包'], category:'飼料', building:'烹飪鍋'},
    {name:'北境骨龍飼料*110', mat:['冰精' ,'冰龍涎草','北極鱈魚'], category:'飼料', building:'烹飪鍋'},
    {name:'大閘蟹釣魚餌', mat:['大閘蟹' ,'小麥飼料包'], category:'飼料', building:'烹飪鍋'},
    {name:'小龍蝦釣魚餌', mat:['小龍蝦' ,'小麥飼料包'], category:'飼料', building:'烹飪鍋'},
    {name:'蟹肉煲', mat:['帝王蟹' ,'朝天椒', '生雞腿'], satiety:135, category:'吃的', building:'烹飪鍋'},
    {name:'乾煸豆角', mat:['黃豆' ,'朝天椒', '胡椒'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'檸檬蒸冰魚', mat:['北極冰魚' ,'檸檬', '辣椒'], satiety:60, hydration:30, category:'吃的', building:'烹飪鍋'},
    {name:'芙蓉冰魚片', mat:['北極冰魚' ,'白蓮'], satiety:40, hydration:50, category:'吃的', building:'烹飪鍋'},
    {name:'胡蘿蔔燜冰魚', mat:['北極冰魚' ,'胡蘿蔔'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'紅燒冰魚', mat:['北極冰魚' ,'辣椒', '薑'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'清蒸冰魚', mat:['北極冰魚' ,'薑', '白蓮'], satiety:70, hydration:20, category:'吃的', building:'烹飪鍋'},
    {name:'土豆燒帶魚', mat:['帶魚' ,'土豆', '胡椒'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'浪花東星斑', mat:['東星斑魚', '辣椒', '青椒'], satiety:65, effect:'禦寒', category:'吃的', building:'烹飪鍋'},
    {name:'翡翠東星斑', mat:['東星斑魚', '菠菜'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'珠簾東星斑', mat:['東星斑魚', '生雞蛋','辣椒'], satiety:75, category:'吃的', building:'烹飪鍋'},
    {name:'清蒸東星斑', mat:['東星斑魚', '薑'], satiety:65, category:'吃的', building:'烹飪鍋'},
    {name:'蘑菇燉河豚', mat:['河豚', '蘑菇', '薑'], satiety:60, hydration:20, category:'吃的', building:'烹飪鍋'},
    {name:'炸河豚塊', mat:['河豚', '胡椒'], satiety:55, category:'吃的', building:'烹飪鍋'},
    {name:'虎斑炒蘿蔔', mat:['老虎斑魚', '胡蘿蔔'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'清蒸虎斑魚', mat:['老虎斑魚', '薑'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'胡椒鯉魚尾', mat:['鯉魚','胡椒'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'芙蓉虎星斑', mat:['老虎斑魚','東星斑魚','白蓮'], satiety:85, category:'吃的', building:'烹飪鍋'},
    {name:'清蒸帝王蟹', mat:['帝王蟹','薑'], satiety:90, category:'吃的', building:'烹飪鍋'},
    {name:'香辣帝王蟹', mat:['帝王蟹','辣椒','薑'], satiety:90, category:'吃的', building:'烹飪鍋'},
    {name:'茄汁鮫魚', mat:['鮫魚','番茄','薑'], satiety:70, category:'吃的', building:'烹飪鍋'},
    {name:'帝王琵琶鍋', mat:['帝王蟹','大龍蝦','薑'], satiety:105,effect:'禦寒',category:'吃的', building:'烹飪鍋'},
    {name:'扇貝意大利面', mat:['大扇貝','小麥','蘑菇'], satiety:50, hydration:20, category:'吃的', building:'烹飪鍋'},
    {name:'松鼠的小零食', mat:['松果','冰河松果'], satiety:40,effect:'加速',category:'吃的', building:'烹飪鍋'},
    {name:'胡辣冰魚湯', mat:['北極冰魚','辣椒','胡椒'], satiety:45,effect:'禦寒',category:'喝的', building:'烹飪鍋'},
    {name:'玫瑰香蕉奶昔', mat:['玫瑰茄','香蕉','牛奶'], satiety:40, hydration:40, category:'喝的', building:'烹飪鍋'},
    {name:'玫瑰檸檬茶', mat:['玫瑰茄','檸檬'], satiety:20, hydration:60, category:'喝的', building:'烹飪鍋'},
    {name:'蘿蔔鮮貝湯', mat:['胡蘿蔔','大扇貝','薑'], satiety:50, hydration:30, category:'喝的', building:'烹飪鍋'},
    {name:'白蓮牛汁湯', mat:['白蓮','生牛排','胡蘿蔔'], satiety:40, hydration:50, category:'喝的', building:'烹飪鍋'},
    {name:'芙蓉菠菜湯', mat:['白蓮','菠菜'], satiety:50, hydration:40, category:'喝的', building:'烹飪鍋'},
    {name:'菠菜鯉魚湯', mat:['菠菜','鯉魚'], satiety:45, category:'喝的', building:'烹飪鍋'},
    {name:'桃可豆奶茶', mat:['可可豆','桃子','牛奶'], satiety:30, hydration:50, category:'喝的', building:'烹飪鍋'},
    {name:'章魚沙拉', mat:['章魚','土豆','玉米'], satiety:50, hydration:20, category:'吃的', building:'烹飪鍋'},
    {name:'椒鹽銀鯧魚', mat:['烤辣椒','朝天椒','銀鯧魚'], satiety:90, category:'吃的', building:'烹飪鍋'},
    {name:'清蒸綠鯉魚', mat:['綠鯉魚','土豆','薑'], satiety:70, hydration:20, category:'吃的', building:'烹飪鍋'},
    {name:'黃桃罐頭', mat:['甘蔗','桃子'], satiety:40, hydration:15, category:'吃的', building:'烹飪鍋'},
    {name:'四喜丸子', mat:['生雞蛋','胡椒','野味肉塊'], satiety:55, category:'吃的', building:'烹飪鍋'},
    {name:'脆炸香蕉', mat:['小麥','雞蛋','香蕉'], satiety:50, hydration:-5, category:'吃的', building:'烹飪鍋'},
    {name:'芙蓉蟹肉', mat:['帝王蟹','小龍蝦','生豬肉'], satiety:70, category:'吃的', building:'烹飪鍋'},
    {name:'野味串燒', mat:['野味肉塊','龜蛋','珍珠'], satiety:50, hydration:10, category:'吃的', building:'烹飪鍋'},
    {name:'揚州炒飯', mat:['小龍蝦','生雞蛋','玉米'], satiety:70, category:'吃的', building:'烹飪鍋'},
    {name:'葡萄果醬', mat:['葡萄','葡萄'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'蜜桃果醬', mat:['桃子','桃子'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'泰式冬陰功湯', mat:['小龍蝦','小扇貝','香茅'], satiety:80, hydration:50, category:'喝的', building:'烹飪鍋'},
    {name:'絲滑蝦球', mat:['甘蔗','玉米','小龍蝦'], satiety:70, category:'吃的', building:'烹飪鍋'},
    {name:'魚頭泡餅', mat:['綠鱸魚','鮁魚','小麥'], satiety:80, hydration:35, category:'吃的', building:'烹飪鍋'},
    {name:'牛肉飯糰', mat:['生牛排','海帶','小麥'], satiety:85, category:'吃的', building:'烹飪鍋'},
    {name:'沙灘野味', mat:['烤野味','烤龜蛋','葡萄'], satiety:110, hydration:20, category:'吃的', building:'烹飪鍋'},
    {name:'可樂餅', mat:['小麥','洋蔥','土豆'], satiety:40, hydration:-10, category:'吃的', building:'烹飪鍋'},
    {name:'檸檬派', mat:['小麥','甘蔗','檸檬'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'海帶豆腐蝦湯', mat:['海帶','黃豆','小龍蝦'], satiety:80, hydration:40, category:'喝的', building:'烹飪鍋'},
    {name:'乾鍋牛蛙', mat:['土豆','竹筍','牛蛙'], satiety:105, category:'吃的', building:'烹飪鍋'},
    {name:'清蒸銀鯧魚', mat:['銀鯧魚','土豆','竹筍'], satiety:60, hydration:30, category:'吃的', building:'烹飪鍋'},
    {name:'檸檬雞', mat:['朝天椒','檸檬','雞腿'], satiety:100, effect:'禦寒', category:'吃的', building:'烹飪鍋'},
    {name:'辣子雞丁', mat:['烤雞腿','烤辣椒'], satiety:60, effect:'禦寒', category:'吃的', building:'烹飪鍋'},
    {name:'清蒸小丑魚', mat:['小丑魚','土豆','竹筍'], satiety:60, hydration:30, category:'吃的', building:'烹飪鍋'},
    {name:'爆炒魷魚', mat:['章魚','青椒','洋蔥'], satiety:70, category:'吃的', building:'烹飪鍋'},
    {name:'淘汰郎火鍋', mat:['菠菜','辣椒','生牛排'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'先秦肉夾饃', mat:['小麥','烤豬排','胡椒'], satiety:70, category:'吃的', building:'烹飪鍋'},
    {name:'滑蛋牛柳', mat:['生牛排','生雞蛋'], satiety:45, hydration:5, category:'吃的', building:'烹飪鍋'},
    {name:'羊排飯團', mat:['烤羊排','海帶','小麥'], satiety:70, category:'吃的', building:'烹飪鍋'},
    {name:'柚子檸檬茶', mat:['柑橘','檸檬','蜂蜜'], satiety:50, hydration:35, category:'喝的', building:'烹飪鍋'},
    {name:'香茅醬', mat:['香茅','朝天椒','薑'], satiety:105,effect: '耐力', category:'吃的', building:'烹飪鍋'},
    {name:'松果蛋糕', mat:['小麥','牛奶','松果'], satiety:65, hydration:-5, category:'吃的', building:'烹飪鍋'},
    {name:'小丑魚刺身', mat:['番茄','檸檬','小丑魚'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'茄汁綠驢魚', mat:['綠驢魚','番茄','洋蔥'], satiety:75, category:'吃的', building:'烹飪鍋'},
    {name:'咖哩龜蛋', mat:['洋蔥','胡椒','龜蛋'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'藍蘑菇湯', mat:['藍蘑菇','牛奶'], satiety:35, hydration:50,effect: '耐熱', category:'喝的', building:'烹飪鍋'},
    {name:'紅蘑菇湯', mat:['紅蘑菇','牛奶'], satiety:35, hydration:50,effect: '禦寒', category:'喝的', building:'烹飪鍋'},
    {name:'麻婆豆腐', mat:['生豬排','辣椒','黃豆'], satiety:55, category:'吃的', building:'烹飪鍋'},
    {name:'南瓜咖哩雞', mat:['南瓜','烤雞腿','烤蘑菇'], satiety:75, category:'吃的', building:'烹飪鍋'},
    {name:'香炸龍蝦球', mat:['小龍蝦','小麥'], satiety:100, category:'吃的', building:'烹飪鍋'},
    {name:'麻辣土豆絲', mat:['辣椒','土豆'], satiety:75, category:'吃的', building:'烹飪鍋'},
    {name:'培根土豆泥', mat:['蘑菇','土豆'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'玫瑰茄醬', mat:['甘蔗','玫瑰茄'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'香芋蒸排骨', mat:['芋頭','生豬排'], satiety:65, hydration:10, category:'吃的', building:'烹飪鍋'},
    {name:'酸湯桂魚', mat:['桂魚','番茄','蘑菇'], satiety:70, hydration:15, category:'吃的', building:'烹飪鍋'},
    {name:'蒲燒鰻魚', mat:['鰻魚','甘蔗','洋蔥'], satiety:75, category:'吃的', building:'烹飪鍋'},
    {name:'菌類靈魚湯', mat:['精靈魚','蘑菇','竹筍'], satiety:220, hydration:50,effect: '攻擊', category:'吃的', building:'烹飪鍋'},
    {name:'靚膚彩蓮湯', mat:['白蓮','紅蓮','藍蓮'], satiety:260, category:'吃的', building:'烹飪鍋'},
    {name:'紅鯉魚與綠鯉魚', mat:['紅鯉魚','綠鯉魚'], satiety:85, hydration:35, category:'吃的', building:'烹飪鍋'},
    {name:'河豚刺身', mat:['河豚','番茄','檸檬'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'藍莓果醬', mat:['藍莓','藍莓'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'草莓果醬', mat:['草莓','草莓'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'辛香匯水煮牛蛙', mat:['朝天椒','胡椒','牛蛙'], satiety:105, category:'吃的', building:'烹飪鍋'},
    {name:'秘汁焗斑魚', mat:['東星斑魚','蜂蜜','烤雞腿'], satiety:90, category:'吃的', building:'烹飪鍋'},
    {name:'清涼水果匯', mat:['檸檬','蘋果','甘蔗'], satiety:40, hydration:50,effect: '耐熱', category:'喝的', building:'烹飪鍋'},
    {name:'香蕉派', mat:['小麥','香蕉','生雞蛋'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'胡蘿蔔滑蛋', mat:['胡蘿蔔','烤雞蛋','黃豆'], satiety:80, category:'吃的', building:'烹飪鍋'},
    {name:'番茄玉米羊湯', mat:['番茄','玉米','生羊排'], satiety:50, hydration:35, category:'喝的', building:'烹飪鍋'},
    {name:'西紅柿羊肉面', mat:['番茄','生羊排','小麥'], satiety:65, hydration:15, category:'吃的', building:'烹飪鍋'},
    {name:'西紅柿炒蛋', mat:['番茄','生雞蛋'], satiety:45, hydration:5, category:'吃的', building:'烹飪鍋'},
    {name:'三文魚漢堡', mat:['三文魚','小麥','番茄'], satiety:85, hydration:10, category:'吃的', building:'烹飪鍋'},
    {name:'三文魚刺身', mat:['三文魚','番茄'], satiety:45, hydration:20, category:'吃的', building:'烹飪鍋'},
    {name:'豬排漢堡', mat:['烤豬排','小麥','番茄'], satiety:70, category:'吃的', building:'烹飪鍋'},
    {name:'魷魚漢堡', mat:['烤章魚','小麥','番茄'], satiety:70, hydration:10, category:'吃的', building:'烹飪鍋'},
    {name:'野味漢堡', mat:['烤野味','小麥','番茄'], satiety:70, category:'吃的', building:'烹飪鍋'},
    {name:'牛排漢堡', mat:['烤牛排','小麥','番茄'], satiety:75, category:'吃的', building:'烹飪鍋'},
    {name:'經典漢堡', mat:['烤雞腿','小麥','番茄'], satiety:65, category:'吃的', building:'烹飪鍋'},
    {name:'象拔蚌刺身', mat:['象拔蚌','番茄'], satiety:100, hydration:20, category:'吃的', building:'烹飪鍋'},
    {name:'炸洋蔥圈', mat:['洋蔥','番茄','生雞蛋'], satiety:40, hydration:-10, category:'吃的', building:'烹飪鍋'},
    {name:'金槍魚漢堡', mat:['金槍魚','小麥','番茄'], satiety:60, hydration:10, category:'吃的', building:'烹飪鍋'},
    {name:'鮮芋仙芋圓4號', mat:['芋頭','紅豆'], satiety:60, hydration:30, category:'吃的', building:'烹飪鍋'},
    {name:'玉米豬排', mat:['生豬排','玉米'], satiety:45, hydration:25, category:'吃的', building:'烹飪鍋'},
    {name:'蘑菇豬排', mat:['蘑菇','烤豬排'], satiety:55, category:'吃的', building:'烹飪鍋'},
    {name:'鮫魚餃子', mat:['鮫魚','小麥'], satiety:80, hydration:5, category:'吃的', building:'烹飪鍋'},
    {name:'辣炒鮫魚', mat:['鮫魚','烤辣椒','薑'], satiety:90, category:'吃的', building:'烹飪鍋'},
    {name:'荷花魚翅', mat:['白蓮','菠菜','鮫魚'], satiety:80, hydration:50, category:'吃的', building:'烹飪鍋'},
    {name:'紅豆蓮子羹', mat:['白蓮','小麥','紅豆'], satiety:30, hydration:60,effect: '耐熱', category:'吃的', building:'烹飪鍋'},
    {name:'雞排(綁定)', mat:[], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'鮑魚撈飯', mat:['鮑魚','胡蘿蔔','蘑菇'], satiety:105, hydration:50,effect: '血量', category:'吃的', building:'烹飪鍋'},
    {name:'多汁鮑魚', mat:['鮑魚','南瓜','蜂蜜'], satiety:105, hydration:60,effect: '耐力', category:'吃的', building:'烹飪鍋'},
    {name:'晨夕養生湯', mat:['菠菜','海帶','胡蘿蔔'], satiety:50, hydration:40, category:'吃的', building:'烹飪鍋'},
    {name:'菠菜炒蛋', mat:['菠菜','黃豆','生雞蛋'], satiety:75, hydration:20, category:'吃的', building:'烹飪鍋'},
    {name:'下品菠菜炒蛋', mat:['菠菜','生雞蛋'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'口水雞', mat:['菠菜','生雞腿','黃豆'], satiety:55, category:'吃的', building:'烹飪鍋'},
    {name:'怪味肉塊', mat:['飼喂肉塊','生牛排'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'果醬', mat:['草莓','藍莓'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'草莓果茶', mat:['草莓','玫瑰茄','蘋果'], satiety:40, hydration:80, category:'喝的', building:'烹飪鍋'},
    {name:'草莓牛奶', mat:['草莓','牛奶'], satiety:30, hydration:40, category:'喝的', building:'烹飪鍋'},
    {name:'草莓蛋糕', mat:['草莓','牛奶','小麥'], satiety:65, hydration:-5, category:'吃的', building:'烹飪鍋'},
    {name:'怪味零食', mat:['飼喂肉塊','章魚','生牛肉'], satiety:45, hydration:30, category:'吃的', building:'烹飪鍋'},
    {name:'草莓派', mat:['草莓','小麥'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'松仁玉米', mat:['松果','胡蘿蔔','玉米'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'草莓椰果', mat:['草莓','椰子'], satiety:40, hydration:25, category:'喝的', building:'烹飪鍋'},
    {name:'松子魚湯', mat:['松果','青斑魚','薑'], satiety:70, hydration:30, category:'喝的', building:'烹飪鍋'},
    {name:'松仁玉米粥', mat:['松果','玉米','甘蔗'], satiety:50, hydration:20, category:'吃的', building:'烹飪鍋'},
    {name:'草莓奶茶', mat:['草莓','珍珠','牛奶'], satiety:45, hydration:30, category:'喝的', building:'烹飪鍋'},
    {name:'松露玉簪蝦球', mat:['松露','小龍蝦','小麥'], satiety:100, category:'吃的', building:'烹飪鍋'},
    {name:'椒香牛柳', mat:['朝天椒','胡椒','生牛排'], satiety:105,effect: '禦寒', category:'吃的', building:'烹飪鍋'},
    {name:'清蒸大龍蝦', mat:['大龍蝦','番茄','烤南瓜'], satiety:100,effect: '血量', category:'吃的', building:'烹飪鍋'},
    {name:'蜜桃果醬', mat:['桃子','桃子'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'黃桃牛奶', mat:['桃子','牛奶'], satiety:40, hydration:40, category:'喝的', building:'烹飪鍋'},
    {name:'水果沙拉', mat:['桃子','西瓜','蘋果'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'清蒸大蝦', mat:['大龍蝦','薑','胡椒'], satiety:70, category:'吃的', building:'烹飪鍋'},
    {name:'龍蝦小丸子', mat:['大龍蝦','小麥'], satiety:100, category:'吃的', building:'烹飪鍋'},
    {name:'黃桃派', mat:['桃子','小麥'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'紅菇大蝦包（未綁定）', mat:['大龍蝦','小麥','紅蘑菇'], satiety:105,effect: '禦寒', category:'吃的', building:'烹飪鍋'},
    {name:'紅菇大蝦包（綁定）', mat:['大龍蝦','小麥','紅蘑菇'], satiety:150,effect: '禦寒', category:'吃的', building:'烹飪鍋'},
    {name:'黃桃奶茶', mat:['桃子','珍珠','牛奶'], satiety:45, hydration:30, category:'喝的', building:'烹飪鍋'},
    {name:'藍菇大蝦包', mat:['大龍蝦','小麥','藍蘑菇'], satiety:105,effect: '禦寒', category:'吃的', building:'烹飪鍋'},
    {name:'咖喱牛肉', mat:['土豆','洋蔥','生牛排'], satiety:45, category:'吃的', building:'烹飪鍋'},
    {name:'吉利蝦', mat:['大龍蝦','洋蔥','胡椒'], satiety:105,effect: '血量', category:'吃的', building:'烹飪鍋'},
    {name:'怪味麻辣肉', mat:['土豆飼料包','黃豆飼料包','辣椒飼料包'], satiety:55, category:'吃的', building:'烹飪鍋'},
    {name:'西瓜沙冰', mat:['西瓜','蜂蜜'], satiety:40, hydration:30, category:'吃的', building:'烹飪鍋'},
    {name:'大貝披薩', mat:['大扇貝','小麥','青椒'], satiety:40, hydration:10, category:'吃的', building:'烹飪鍋'},
    {name:'西瓜牛奶', mat:['西瓜','牛奶'], satiety:40, hydration:30, category:'喝的', building:'烹飪鍋'},
    {name:'香炸蟹腿', mat:['大閘蟹','小麥'], satiety:65, hydration:-5, category:'吃的', building:'烹飪鍋'},
    {name:'金裝水果樂園', mat:['西瓜','葡萄','草莓'], satiety:50, hydration:40, category:'喝的', building:'烹飪鍋'},
    {name:'糖醋帶魚', mat:['帶魚','甘蔗'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'西瓜奶茶', mat:['西瓜','珍珠','牛奶'], satiety:45, hydration:30, category:'喝的', building:'烹飪鍋'},
    {name:'辣炒帶魚', mat:['帶魚','烤辣椒','薑'], satiety:90, category:'吃的', building:'烹飪鍋'},
    {name:'芋頭燒帶魚', mat:['帶魚','青椒','芋頭'], satiety:80, category:'吃的', building:'烹飪鍋'},
    {name:'剁椒蒸帶魚', mat:['帶魚','青椒','竹筍'], satiety:105,effect: '禦寒', category:'吃的', building:'烹飪鍋'},
    {name:'東星斑魚鍋', mat:['東星斑魚','胡椒','洋蔥'], satiety:80, hydration:10, category:'吃的', building:'烹飪鍋'},
    {name:'魚香肉絲飯', mat:['東星斑魚','小麥','烤豬排'], satiety:90, category:'吃的', building:'烹飪鍋'},
    {name:'松鼠桂魚', mat:['香蕉','蜂蜜','桂魚'], satiety:70, category:'吃的', building:'烹飪鍋'},
    {name:'酸湯斑魚', mat:['東星斑魚','竹筍','番茄'], satiety:60, hydration:30, category:'吃的', building:'烹飪鍋'},
    {name:'香蕉牛奶', mat:['香蕉','牛奶'], satiety:40, hydration:10, category:'喝的', building:'烹飪鍋'},
    {name:'海南雞', mat:['香茅','檸檬','生雞腿'], satiety:55, category:'吃的', building:'烹飪鍋'},
    {name:'番茄醬', mat:['番茄', '番茄'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'番茄魚丸湯', mat:['番茄','鯉魚'], satiety:40, hydration:20, category:'吃的', building:'烹飪鍋'},
    {name:'象拔蚌撈飯', mat:['象拔蚌','胡蘿蔔','蘑菇'], satiety:105, hydration:50,effect: '血量', category:'吃的', building:'烹飪鍋'},
    {name:'薯條', mat:['番茄','土豆'], satiety:45, hydration:-10, category:'吃的', building:'烹飪鍋'},
    {name:'蚵仔煎', mat:['象拔蚌','生雞蛋','胡椒'], satiety:105, hydration:30,effect: '血量', category:'吃的', building:'烹飪鍋'},
    {name:'蜂蜜照燒雞', mat:['蜂蜜','甘蔗','雞腿'], satiety:50, hydration:10, category:'吃的', building:'烹飪鍋'},
    {name:'蜂蜜蛋糕', mat:['蜂蜜','牛奶','小麥'], satiety:85, hydration:-5, category:'吃的', building:'烹飪鍋'},
    {name:'蜂蜜雞蛋羹', mat:['蜂蜜','生雞蛋'], satiety:70, hydration:25, category:'吃的', building:'烹飪鍋'},
    {name:'雙皮奶', mat:['甘蔗','生雞蛋','牛奶'], satiety:50, hydration:15, category:'喝的', building:'烹飪鍋'},
    {name:'西瓜汁', mat:['甘蔗','西瓜'], hydration:40, category:'喝的', building:'烹飪鍋'},
    {name:'柑橘罐頭', mat:['柑橘','甘蔗'], satiety:40, hydration:20, category:'吃的', building:'烹飪鍋'},
    {name:'柑橘可可蛋糕', mat:['柑橘','可可豆','小麥'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'蜜橘果茶', mat:['柑橘','香茅','蘋果'], satiety:40, hydration:80, category:'喝的', building:'烹飪鍋'},
    {name:'柑橘可麗餅', mat:['柑橘','小麥','牛奶'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'辣炒桂魚', mat:['桂魚','烤辣椒','薑'], satiety:90, category:'吃的', building:'烹飪鍋'},
    {name:'海帶蓮子湯', mat:['海帶','紅蓮','白蓮'], satiety:60, category:'喝的', building:'烹飪鍋'},
    {name:'蓮子羊湯', mat:['海帶','生羊排','藍蓮'], satiety:60, category:'喝的', building:'烹飪鍋'},
    {name:'怪味魚肉', mat:['河豚','鯰魚'], satiety:35, hydration:30, category:'吃的', building:'烹飪鍋'},
    {name:'豆沙包', mat:['紅豆','小麥'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'八寶粥', mat:['紅豆','玉米','甘蔗'], satiety:45, hydration:20, category:'吃的', building:'烹飪鍋'},
    {name:'川椒鯉魚', mat:['紅鯉魚','綠鯉魚','辣椒'], satiety:90, category:'吃的', building:'烹飪鍋'},
    {name:'紅燒紅鯉魚', mat:['紅鯉魚','小麥'], satiety:80, category:'吃的', building:'烹飪鍋'},
    {name:'蝦兵蟹將', mat:['小龍蝦','大閘蟹'], satiety:110,effect: '耐力', category:'吃的', building:'烹飪鍋'},
    {name:'紅菇小蝦包', mat:['小龍蝦','小麥','紅蘑菇'], satiety:80, category:'吃的', building:'烹飪鍋'},
    {name:'藍菇小蝦包', mat:['小龍蝦','小麥','藍蘑菇'], satiety:80, category:'吃的', building:'烹飪鍋'},
    {name:'蘑菇小蝦包', mat:['小龍蝦','小麥','蘑菇'], satiety:85, category:'吃的', building:'烹飪鍋'},
    {name:'辛香匯水煮魚', mat:['胡椒','朝天椒','鯰魚'], satiety:100, effect: '禦寒', category:'吃的', building:'烹飪鍋'},
    {name:'絲滑鐵肘子', mat:['胡椒','黃豆','生豬排'], satiety:55, category:'吃的', building:'烹飪鍋'},
    {name:'蛋黃蓮蓉月餅', mat:['小麥','白蓮','生雞蛋'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'清蒸小童子雞', mat:['胡椒','生雞腿','胡蘿蔔'], satiety:55, hydration:10, category:'吃的', building:'烹飪鍋'},
    {name:'翡翠月餅', mat:['小麥','菠菜','牛奶'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'藤椒牛蛙', mat:['胡椒','檸檬','牛蛙'], satiety:70, category:'吃的', building:'烹飪鍋'},
    {name:'水果月餅', mat:['小麥','草莓','蘋果'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'福源肉丸', mat:['胡椒','小麥','生豬排'], satiety:55, category:'吃的', building:'烹飪鍋'},
    {name:'烤雞蛋布丁', mat:['烤雞蛋','牛奶'], satiety:60, hydration:10, category:'吃的', building:'烹飪鍋'},
    {name:'黃金玉米烙', mat:['小麥','玉米','蜂蜜'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'蛋黃小丸子', mat:['烤雞蛋','小麥'], satiety:55, category:'吃的', building:'烹飪鍋'},
    {name:'玉米月餅', mat:['小麥','玉米','南瓜'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'紫薯蓮蓉月餅', mat:['小麥','芋頭','白蓮'], satiety:65, category:'吃的', building:'烹飪鍋'},
    {name:'蜜汁雞腿', mat:['烤雞腿','蜂蜜'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'雞排飯團', mat:['烤雞腿','海帶','小麥'], satiety:65, category:'吃的', building:'烹飪鍋'},
    {name:'麻辣小龍蝦', mat:['烤辣椒','小龍蝦'], satiety:80, category:'吃的', building:'烹飪鍋'},
    {name:'牛排飯團', mat:['烤牛排','海帶','小麥'], satiety:70, category:'吃的', building:'烹飪鍋'},
    {name:'蔬菜串燒', mat:['烤蘋果','烤香蕉','烤玉米'], satiety:85, category:'吃的', building:'烹飪鍋'},
    {name:'蜜汁烤羊排', mat:['烤羊排','蜂蜜'], satiety:65, hydration:-5, category:'吃的', building:'烹飪鍋'},
    {name:'扇貝蒸蛋', mat:['小扇貝','生雞蛋'], satiety:60, hydration:20, category:'吃的', building:'烹飪鍋'},
    {name:'小貝披薩', mat:['小扇貝','小麥','青椒'], satiety:35, hydration:10, category:'吃的', building:'烹飪鍋'},
    {name:'章魚小丸子', mat:['烤章魚','小麥'], satiety:55, category:'吃的', building:'烹飪鍋'},
    {name:'大鵬雞腿', mat:['洋蔥','胡椒','生雞腿'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'大牌滷肉', mat:['洋蔥','胡椒','生豬排'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'肉醬土豆泥', mat:['烤豬排','烤土豆','牛奶'], satiety:130, category:'吃的', building:'烹飪鍋'},
    {name:'魔法怪味豆', mat:['洋蔥','黃豆','胡椒'], category:'吃的', building:'烹飪鍋'},
    {name:'豬排厚蛋燒', mat:['烤豬排','生雞蛋','小麥'], satiety:65, category:'吃的', building:'烹飪鍋'},
    {name:'椰子汁', mat:['椰子','甘蔗'], hydration:40, category:'喝的', building:'烹飪鍋'},
    {name:'椰奶', mat:['椰子','牛奶'], satiety:35, hydration:40, category:'喝的', building:'烹飪鍋'},
    {name:'西米露', mat:['椰子','小麥','牛奶'], satiety:45, hydration:50, category:'喝的', building:'烹飪鍋'},
    {name:'野味肉醬', mat:['野味肉塊','黃豆'], satiety:50, hydration:-10, category:'吃的', building:'烹飪鍋'},
    {name:'巧克力醬', mat:['可可豆'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'野味肉醬面', mat:['野味肉塊','黃豆','小麥'], satiety:50, hydration:10, category:'吃的', building:'烹飪鍋'},
    {name:'珍珠奶茶', mat:['可可豆','紅豆','牛奶'], satiety:40, hydration:25, category:'喝的', building:'烹飪鍋'},
    {name:'野味肉包', mat:['野味肉塊','小麥'], satiety:75, category:'吃的', building:'烹飪鍋'},
    {name:'巧克力牛奶', mat:['可可豆','牛奶'], satiety:35, hydration:20, category:'喝的', building:'烹飪鍋'},
    {name:'銀鯧魚魚子醬', mat:['銀鯧魚','白蓮'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'巧克力曲奇', mat:['可可豆','牛奶','小麥'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'紅燒銀鯧魚', mat:['銀鯧魚','胡椒','薑'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'奧爾良小烤', mat:['銀鯧魚','烤雞腿','烤羊排'], satiety:90, category:'吃的', building:'烹飪鍋'},
    {name:'巧克力椰果', mat:['可可豆','椰子'], satiety:40, hydration:20, category:'喝的', building:'烹飪鍋'},
    {name:'香煎銀鯧魚', mat:['銀鯧魚','辣椒','青椒'], satiety:90, category:'吃的', building:'烹飪鍋'},
    {name:'巧克力奶茶', mat:['可可豆','珍珠','牛奶'], satiety:50, hydration:20, category:'喝的', building:'烹飪鍋'},
    {name:'香辣小龍蝦', mat:['辣椒','小龍蝦'], satiety:85, category:'吃的', building:'烹飪鍋'},
    {name:'藍莓果茶', mat:['藍莓','玫瑰茄','蘋果'], satiety:40, hydration:80, category:'喝的', building:'烹飪鍋'},
    {name:'爆米花', mat:['玉米','甘蔗'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'什錦河豚肉丁', mat:['玉米','胡蘿蔔','河豚'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'藍莓牛奶', mat:['藍莓','牛奶'], satiety:30, hydration:40, category:'喝的', building:'烹飪鍋'},
    {name:'玉米珍珠奶茶', mat:['玉米','珍珠','牛奶'], satiety:45, hydration:20, category:'喝的', building:'烹飪鍋'},
    {name:'藍莓蛋糕', mat:['藍莓','牛奶','小麥'], satiety:65, hydration:-5, category:'吃的', building:'烹飪鍋'},
    {name:'蒸芋頭', mat:['芋頭','甘蔗'], satiety:60, hydration:20, category:'喝的', building:'烹飪鍋'},
    {name:'藍莓派', mat:['藍莓','小麥'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'芋頭牛奶', mat:['芋頭','牛奶'], satiety:55, hydration:40, category:'喝的', building:'烹飪鍋'},
    {name:'藍莓椰果', mat:['藍莓','椰子'], satiety:35, hydration:30, category:'喝的', building:'烹飪鍋'},
    {name:'藍莓奶茶', mat:['藍莓','珍珠','牛奶'], satiety:50, hydration:30, category:'喝的', building:'烹飪鍋'},
    {name:'蟹肉宴', mat:['珍珠','大閘蟹','帝王蟹'], satiety:100, category:'吃的', building:'烹飪鍋'},
    {name:'筍釀', mat:['竹筍','蘑菇','生豬排'], satiety:105,effect: '耐力', category:'吃的', building:'烹飪鍋'},
    {name:'問政山筍', mat:['竹筍','洋蔥','蘑菇'], satiety:105,effect: '耐力', category:'吃的', building:'烹飪鍋'},
    {name:'老虎斑魚鍋', mat:['老虎斑魚','胡椒','洋蔥'], satiety:80, hydration:10, category:'吃的', building:'烹飪鍋'},
    {name:'椰子煲魚頭', mat:['老虎斑魚','椰子','薑'], satiety:90, category:'吃的', building:'烹飪鍋'},
    {name:'蘋果果醬', mat:['蘋果'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'糖酥鯉魚', mat:['鯉魚','甘蔗'], satiety:45, hydration:10, category:'吃的', building:'烹飪鍋'},
    {name:'牛蛙煲', mat:['牛蛙','洋蔥','竹筍'], satiety:105, category:'吃的', building:'烹飪鍋'},
    {name:'辣炒鯉魚', mat:['鯉魚','烤辣椒','薑'], satiety:90, category:'吃的', building:'烹飪鍋'},
    {name:'紅燒綠鯉魚', mat:['綠鯉魚','小麥'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'清蒸綠驢魚', mat:['綠驢魚','土豆'], satiety:80, category:'吃的', building:'烹飪鍋'},
    {name:'辣炒鰻魚', mat:['鰻魚','烤辣椒','薑'], satiety:90, category:'吃的', building:'烹飪鍋'},
    {name:'鰻魚飯', mat:['鰻魚','小麥'], satiety:75, category:'吃的', building:'烹飪鍋'},
    {name:'洛神奶凍', mat:['玫瑰茄','牛奶','生雞蛋'], satiety:50, hydration:5, category:'吃的', building:'烹飪鍋'},
    {name:'蜜桃果茶', mat:['玫瑰茄','桃子','蘋果'], satiety:40, hydration:80, category:'喝的', building:'烹飪鍋'},
    {name:'蘑菇大蝦包', mat:['蘑菇','大龍蝦','小麥'], satiety:105,effect: '耐力', category:'吃的', building:'烹飪鍋'},
    {name:'黃燜雞', mat:['蘑菇','青椒','生雞腿'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'南瓜粥', mat:['南瓜','甘蔗','玉米'], satiety:50, hydration:20, category:'吃的', building:'烹飪鍋'},
    {name:'南瓜起司烘蛋', mat:['南瓜','生雞蛋','小麥'], satiety:70, category:'吃的', building:'烹飪鍋'},
    {name:'蛋黃焗南瓜', mat:['南瓜','烤雞蛋'], satiety:55, category:'吃的', building:'烹飪鍋'},
    {name:'南瓜小丸子', mat:['南瓜','小麥'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'南瓜鬆餅', mat:['南瓜','小麥','牛奶'], satiety:55, category:'吃的', building:'烹飪鍋'},
    {name:'豆腐燒鯰魚', mat:['鯰魚','黃豆'], satiety:40, hydration:20, category:'吃的', building:'烹飪鍋'},
    {name:'辣炒鯰魚', mat:['鯰魚','烤辣椒','薑'], satiety:90, category:'吃的', building:'烹飪鍋'},
    {name:'香酥魚片', mat:['鯰魚','小麥'], satiety:45, hydration:-5, category:'吃的', building:'烹飪鍋'},
    {name:'蜂蜜檸檬水', mat:['檸檬','甘蔗','蜂蜜'], satiety:30, hydration:40, category:'喝的', building:'烹飪鍋'},
    {name:'奶油蘑菇湯', mat:['牛奶','蘑菇'], satiety:45, hydration:30, category:'喝的', building:'烹飪鍋'},
    {name:'牛肉醬', mat:['牛肉','黃豆'], satiety:50, hydration:-10, category:'吃的', building:'烹飪鍋'},
    {name:'拔絲蘋果', mat:['蘋果','甘蔗'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'生薑果茶', mat:['蘋果','薑','玫瑰茄'], satiety:40, hydration:80, category:'喝的', building:'烹飪鍋'},
    {name:'香檸果茶', mat:['蘋果','香茅','檸檬'], satiety:40, hydration:80, category:'喝的', building:'烹飪鍋'},
    {name:'蘋果派', mat:['蘋果','小麥'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'葡萄果醬', mat:['葡萄'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'葡萄酒', mat:['葡萄','甘蔗'], satiety:30, hydration:40, category:'喝的', building:'烹飪鍋'},
    {name:'葡萄奶酥', mat:['葡萄','牛奶','生雞蛋'], satiety:50, category:'吃的', building:'烹飪鍋'},
    {name:'一清二白', mat:['青斑魚','黃豆'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'麻辣桂魚', mat:['青椒','桂魚'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'黑椒羊排', mat:['青椒','胡椒','烤羊排'], satiety:70, category:'吃的', building:'烹飪鍋'},
    {name:'絕代三椒', mat:['青椒','辣椒','胡椒'], satiety:60,effect: '禦寒', category:'吃的', building:'烹飪鍋'},
    {name:'青椒炒蛋', mat:['青椒','生雞蛋'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'爆炒牛蛙', mat:['青椒','洋蔥','牛蛙'], satiety:70, category:'吃的', building:'烹飪鍋'},
    {name:'三文魚通心粉', mat:['三文魚','牛奶','小麥'], satiety:100, hydration:30,effect: '耐力', category:'吃的', building:'烹飪鍋'},
    {name:'香煎帶魚', mat:['洋蔥','小麥','帶魚'], satiety:55, category:'吃的', building:'烹飪鍋'},
    {name:'章魚腿刺身', mat:['章魚','番茄'], satiety:40, hydration:20, category:'吃的', building:'烹飪鍋'},
    {name:'單身狗糧', mat:['龜蛋','生雞蛋'], satiety:40, category:'吃的', building:'烹飪鍋'},
    {name:'辛香匯缽缽雞', mat:['生雞腿','朝天椒','胡椒'], satiety:100,effect: '禦寒', category:'吃的', building:'烹飪鍋'},
    {name:'雞肉飯團', mat:['生雞腿','海帶','小麥'], satiety:75, category:'吃的', building:'烹飪鍋'},
    {name:'小雞燉蘑菇', mat:['生雞腿','蘑菇'], satiety:45, hydration:10, category:'吃的', building:'烹飪鍋'},
    {name:'香煎牛排', mat:['生牛排','番茄'], satiety:45, hydration:-5, category:'吃的', building:'烹飪鍋'},
    {name:'牛肉包', mat:['生牛排','小麥'], satiety:70, category:'吃的', building:'烹飪鍋'},
    {name:'羊排湯', mat:['生羊排','胡蘿蔔'], satiety:45, hydration:35, category:'吃的', building:'烹飪鍋'},
    {name:'排骨', mat:['生豬排','番茄'], satiety:45, hydration:35, category:'吃的', building:'烹飪鍋'},
    {name:'海帶排骨湯', mat:['生豬排','海帶'], satiety:45, hydration:40, category:'吃的', building:'烹飪鍋'},
    {name:'豬肉飯團', mat:['生豬排','海帶','小麥'], satiety:85, category:'吃的', building:'烹飪鍋'},
    {name:'辣椒炒肉', mat:['生豬排','辣椒'], satiety:60, category:'吃的', building:'烹飪鍋'},
    {name:'大亂燉', mat:['生豬排','生羊排','生牛排'], satiety:50, hydration:10, category:'吃的', building:'烹飪鍋'},
    {name:'豬肉包', mat:['生豬排','小麥'], satiety:70, category:'吃的', building:'烹飪鍋'},
    {name:'芝士焗蟹', mat:['帝王蟹','蜂蜜','牛奶'], satiety:80, category:'吃的', building:'烹飪鍋'},
];